-- ═══════════════════════════════════════════════════════════════
-- scripts/build_single.lua — single-file generator (Phase 3).
--
-- Usage (from the repo root):
--   lua_portable/bin/lua.exe scripts/build_single.lua
--
-- Emits agent.lua at the repo root: every src/agent module (plus the
-- six agent.tools.* modules) is embedded as a package.preload entry;
-- src/agent/init.lua is inlined verbatim as the entry body.
--
-- The build output is verified with load() before it is written, and
-- line endings are normalized to LF.
-- ═══════════════════════════════════════════════════════════════

local script_dir = debug.getinfo(1, "S").source:match("^@(.*)[/\\][^/\\]+$") or "."
local ROOT = script_dir .. "/.."

-- Core modules in canonical load order (matches init.lua's require chain).
local MODULES = {
  "agent.json",
  "agent.http",
  "agent.config",
  "agent.session",
  "agent.tools",
  "agent.execute",
  "agent.chat",
  "agent.subagent",
  "agent.interrupt",
  "agent.patch",
  "agent.selftest",
  "agent.debug",
  -- v0.3.116: 宽字符判定区间表（tui.lua require("agent.wcwidth")）——
  -- 单文件构建必须 preload 它, 否则真机 require 失败
  "agent.wcwidth",
  "agent.tui",
}

-- Tool plugin modules (same canonical order as agent.tools BUILTIN).
local TOOL_MODULES = {
  "agent.tools.file",
  "agent.tools.data",
  "agent.tools.component",
  "agent.tools.search",
  "agent.tools.shell",
  "agent.tools.subagent",
  "agent.tools.question",
  "agent.tools.compact",
}

local function read_file(path)
  local f = assert(io.open(path, "rb"), "cannot open " .. path)
  local content = f:read("*a")
  f:close()
  -- normalize to LF regardless of source file line endings
  return (content:gsub("\r\n", "\n"):gsub("\r", "\n"))
end

-- Read a module's source (path = src/agent/<dots→slashes>.lua), trimmed of
-- trailing whitespace. The last line of every module is its `return` — which
-- becomes the preload function's return value, i.e. the require() result.
local function module_source(name)
  local rel = name:gsub("%.", "/") .. ".lua"
  return (read_file(ROOT .. "/src/" .. rel):gsub("%s*$", ""))
end

local out = {}
local function line(s)
  out[#out + 1] = s
end

line("-- ═══════════════════════════════════════════════════════════════")
line("-- OC Agent — AI coding assistant for OpenComputers (GTNH)")
line("-- Single-file build (generated by scripts/build_single.lua).")
line("-- All agent.* modules are embedded as package.preload entries; the")
line("-- entry body is src/agent/init.lua inlined verbatim at the end.")
line("-- ═══════════════════════════════════════════════════════════════")
line("")
line("-- Make the sibling src/agent/ tree require-able (no-op for the")
line("-- preload entries below, but keeps dofile() of this file working")
line("-- when the module files exist on disk, e.g. from the test harness).")
line("do")
line("  local agent_dir = debug.getinfo(1, \"S\").source:match(\"^@(.*)[/\\\\][^/\\\\]+$\")")
line("  if not agent_dir or agent_dir == \"\" then agent_dir = \".\" end")
line("  package.path = agent_dir .. \"/src/?.lua;\" .. package.path")
line("end")
line("")

local function emit_module(name)
  line("-- agent." .. name .. " (embedded module)")
  line("package.preload[\"" .. name .. "\"] = function()")
  line(module_source(name))
  line("end")
  line("")
end

for _, name in ipairs(MODULES) do
  emit_module(name)
end
for _, name in ipairs(TOOL_MODULES) do
  emit_module(name)
end

line("-- ═══════════════════════════════════════════════════════════════")
line("-- Entry: src/agent/init.lua (inlined verbatim)")
line("-- ═══════════════════════════════════════════════════════════════")
line(module_source("agent.init"))

local built = table.concat(out, "\n") .. "\n"

-- Verify the result parses before overwriting the shipped file.
local chunk, err = load(built, "@agent.lua")
if not chunk then
  print("BUILD FAILED (syntax error in generated agent.lua):")
  print(tostring(err))
  os.exit(1)
end

local target = ROOT .. "/agent.lua"
local f = assert(io.open(target, "wb"), "cannot write " .. target)
f:write(built)
f:close()

local nl = 0
for _ in built:gmatch("\n") do nl = nl + 1 end
print("Built " .. target .. ":")
print("  " .. nl .. " lines, " .. #built .. " bytes")
print("  preload modules: " .. (#MODULES + #TOOL_MODULES))
